query ($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      commits(first: 100) {
        nodes {
          ... on PullRequestCommit {
            commit {
              authoredDate
            }
          }
        }
      }
    }
  }
}
