mutation (
  $project: ID!
  $item: ID!
  $status_field: ID!
  $status_value: String!
  $primary_milestone_field: ID!
  $primary_milestone_value: String!
  $secondary_milestone_field: ID!
  $secondary_milestone_value: String!
) {
  status: updateProjectV2ItemFieldValue(
    input: {
      projectId: $project
      itemId: $item
      fieldId: $status_field
      value: { singleSelectOptionId: $status_value }
    }
  ) {
    projectV2Item {
      id
    }
  }
  primary_milestone: updateProjectV2ItemFieldValue(
    input: {
      projectId: $project
      itemId: $item
      fieldId: $primary_milestone_field
      value: { iterationId: $primary_milestone_value }
    }
  ) {
    projectV2Item {
      id
    }
  }
  secondary_milestone: updateProjectV2ItemFieldValue(
    input: {
      projectId: $project
      itemId: $item
      fieldId: $secondary_milestone_field
      value: { iterationId: $secondary_milestone_value }
    }
  ) {
    projectV2Item {
      id
    }
  }
}
