name: Auto-label

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "needs-triage"
          ignore-if-assigned: true
          ignore-if-labeled: true

